"use client";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

export function AboutDialog() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">About</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="font-headline text-primary">The Mandelbrot Set</DialogTitle>
          <DialogDescription className="text-left pt-2">
            A journey into infinite complexity.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 text-muted-foreground">
          <p>
            The Mandelbrot set is one of the most famous examples of a fractal in mathematics.
            It's generated by iterating a simple equation—(z = z² + c)—for every point 'c' on the complex plane.
          </p>
          <p>
            When visualized, the set forms an intricate, infinitely detailed boundary. The colors you see represent how quickly points outside the set escape to infinity. Points inside the set never escape.
          </p>
          <p>
            Use the controls to explore this fascinating mathematical landscape. Zoom in to reveal ever more complex and beautiful patterns!
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
